# Generated by Django 5.2.1 on 2025-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
